services:
  api:
    platform: linux/x86_64
    image: seeding-tutorial/api
    container_name: 'seeding-tutorial-api'
    profiles:
      - all
      - api
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    volumes:
      - ../../services/api:/usr/src/app
    environment:
      API_PROTOCOL: ${API_PROTOCOL}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_DB: ${DATABASE_DB}
      DATABASE_TYPE: ${DATABASE_TYPE}
    ports:
      - '${API_PORT}:${API_PORT}'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT}/health-check || exit 1"]
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
