services:
  database:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: 'seeding-tutorial-database'
    profiles:
      - database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root**password!!
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_INITDB_SKIP_TZINFO=true
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '${DATABASE_PORT}:3306'
    restart: always